### ISSUE TITLE
What's the error that occurred, is it a port issue?

### ISSUE THREAD

**Issue by LTDZ15** [waylaidwanderer/PandoraAI#65]
![000](https://user-images.githubusercontent.com/105056548/230896109-9b372e47-ee7e-47f6-ac27-8e0b3fcfc47a.jpg)
fetch.ts:105 
        
      
        
        
      
        
      
       
        
       POST http://localhost:3001/conversation net::ERR_CONNECTION_REFUSED
create @ fetch.ts:105
(匿名) @ fetch.ts:145
fetchEventSource @ fetch.ts:67
sendMessage @ Chat.vue:322
await in sendMessage(异步)
(匿名) @ Chat.vue:515
(匿名) @ chunk-3NMN3MUW.js?v=1c27165a:9171
(匿名) @ chunk-3NMN3MUW.js?v=1c27165a:9190
callWithErrorHandling @ chunk-3NMN3MUW.js?v=1c27165a:1580
callWithAsyncErrorHandling @ chunk-3NMN3MUW.js?v=1c27165a:1588
invoker @ chunk-3NMN3MUW.js?v=1c27165a:8198
Show 5 more frames
Chat.vue:361 
        
       ERROR TypeError: Failed to fetch
    at create (fetch.ts:105:40)
    at fetch.ts:145:9
    at new Promise (<anonymous>)
    at fetchEventSource (fetch.ts:67:12)
    at Proxy.sendMessage (Chat.vue:322:1)
sendMessage @ Chat.vue:361
await in sendMessage(异步)
(匿名) @ Chat.vue:515
(匿名) @ chunk-3NMN3MUW.js?v=1c27165a:9171
(匿名) @ chunk-3NMN3MUW.js?v=1c27165a:9190
callWithErrorHandling @ chunk-3NMN3MUW.js?v=1c27165a:1580
callWithAsyncErrorHandling @ chunk-3NMN3MUW.js?v=1c27165a:1588
invoker @ chunk-3NMN3MUW.js?v=1c27165a:8198
Show 5 more frames

**Comment by HUAYIXIAO** [comment]
在node-chatgpt-api输入命令行npm run server
