### ISSUE TITLE
while using this webui, can't connect to Bing chat service.

### ISSUE THREAD

**Issue by shereshiia** [waylaidwanderer/PandoraAI#78]
node-chatgpt-api shows bug information 
TypeError: fetch failed
    at Object.fetch (node:internal/deps/undici/undici:11413:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async create (file:///C:/software/node-chatgpt-api-1.35.0/node_modules/@waylaidwanderer/fetch-event-source/lib/esm/fetch.js:52:34) {
  cause: ConnectTimeoutError: Connect Timeout Error
      at onConnectTimeout (C:\software\node-chatgpt-api-1.35.0\node_modules\undici\lib\core\connect.js:182:24)
      at C:\software\node-chatgpt-api-1.35.0\node_modules\undici\lib\core\connect.js:129:46
      at Immediate._onImmediate (C:\software\node-chatgpt-api-1.35.0\node_modules\undici\lib\core\connect.js:168:33)
      at process.processImmediate (node:internal/timers:476:21) {
    code: 'UND_ERR_CONNECT_TIMEOUT'
  }
}

and webui don't show any element. 

<img width="906" alt="屏幕截图 2023-04-14 200654" src="https://user-images.githubusercontent.com/128833861/232039248-af862f6b-85ca-476e-a354-e33a6a21c5f2.png">

**Comment by waylaidwanderer** [comment]
Not related to the frontend client.
